---
### Test the SSHD Config File
### Technically this will exit out and break the Ansible playbook if it fails
- name: Test SSHD Config File
  shell: sshd -t
  register: sshd_results
  ignore_errors: yes

- name: Restart SSHD
  systemd:
    name: sshd
    state: restarted
  when: sshd_results.rc==0
